name = "StatsDiscretizations"
uuid = "1d0cfea5-fabc-4e25-85a8-945fa8abc3c9"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[extensions]
JuMPExt = "JuMP"

[compat]
Dictionaries = "0.4"
Distributions = "0.25"
IntervalSets = "0.7"
JuMP = "1.12"
julia = "1.9"
LogExpFunctions = "0.3"
StatsBase = "0.34"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
